### ISSUE TITLE
warning: scale_weight_norms is specified but the network does not support it / scale_weight_normsが指定されていますが、ネットワークが対応していません

### ISSUE THREAD

**Issue by bmaltais** [KohakuBlueleaf/LyCORIS#57]
Good evening, just a quick question about the new scale_weight_norms option in sd-scripts. Is it something that can be implemented in LyCORIS or it just does not make sens?

**Comment by KohakuBlueleaf** [comment]
@bmaltais Some of then: yes

lokr and IA3 may not support it
for loha this will also be tricky

**Comment by KohakuBlueleaf** [comment]
@bmaltais I do some test on it
locon loha lokr can use this
I will update this

**Comment by KohakuBlueleaf** [comment]
@bmaltais I already add max norm regularization support for locon/loha/lokr
it is in dev branch and you can use python -m pip install --pre lycoris-lora==0.1.7 to install it

I don't have time so you may need to test it if it works at first (

**Comment by KohakuBlueleaf** [comment]
already in Dev branch/dev channel(pypi) and comfirmed working
will close this issue

**Comment by bmaltais** [comment]
Awesome, I will test it today!

**Comment by bmaltais** [comment]
@KohakuBlueleaf I have tested it with LoHA and it appear to report an error regarding tensor size mismatch:

`RuntimeError: The size of tensor a (3) must match the size of tensor b (2880) at non-singleton dimension 3`

For LoCon it appear to train without error.

**Comment by KohakuBlueleaf** [comment]
@bmaltais I just retruend clamped value before
I have pushed a update for this on pypi and dev branch
and for loha I cannot reproduce that error

**Comment by bmaltais** [comment]
I will do some more testing with LoHA then... not sure why I am getting the error. Will pull the new version. Many thanks for the quick response.

**Comment by bmaltais** [comment]
@KohakuBlueleaf I Just tried again with the new release... still give the same error with LoHA... I will provide the log output up to the traceback... maybe you can spot the issue with the arguments? It is possible I am passing some wrong args from the GUI causing the issue:

```
07:37:57-168318 INFO     Start training LoRA LyCORIS/LoHa ...
07:37:57-170318 INFO     Valid image folder names found in: D:\dataset\bernard\img_g4v2
07:37:57-172316 INFO     Folder 30_bmaltais: 23 images found
07:37:57-173318 INFO     Folder 30_bmaltais: 690 steps
07:37:57-174317 INFO     Total steps: 690
07:37:57-175317 INFO     Train batch size: 4
07:37:57-176315 INFO     Gradient accumulation steps: 1
07:37:57-177317 INFO     Epoch: 3
07:37:57-178825 INFO     Regulatization factor: 1
07:37:57-179831 INFO     max_train_steps (690 / 4 / 1 * 3 * 1) = 518
07:37:57-181829 INFO     stop_text_encoder_training = 0
07:37:57-182835 INFO     lr_warmup_steps = 0
07:37:59-153383 INFO     Save...
07:38:03-137003 INFO     accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --enable_bucket --pretrained_model_name_or_path="D:/models/v1-5-pruned.ckpt"
                         --train_data_dir="D:\dataset\bernard\img_g4v2" --resolution="512,512" --output_dir="D:/lycoris" --logging_dir="D:\dataset\bernard\loha/logs" --network_alpha="16"
                         --training_comment="trigger words: bmaltais" --save_model_as=safetensors --network_module=lycoris.kohya --network_args "conv_dim=8" "conv_alpha=4" "use_cp=False" "algo=loha"  
                         --network_dropout="0" --text_encoder_lr=1.0 --unet_lr=1.0 --network_dim=32 --output_name="bmaltais_v2.0c" --lr_scheduler_num_cycles="3" --scale_weight_norms="1"
                         --learning_rate="1.0" --lr_scheduler="cosine" --train_batch_size="4" --max_train_steps="518" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="fp16"        
                         --seed="1234" --caption_extension=".txt" --cache_latents --cache_latents_to_disk --optimizer_type="Prodigy" --optimizer_args decouple=True weight_decay=0.6 betas=0.9,0.99     
                         use_bias_correction=True --max_data_loader_n_workers="0" --bucket_reso_steps=1 --min_snr_gamma=10 --xformers --bucket_no_upscale --multires_noise_iterations="8"
                         --multires_noise_discount="0.2" --wandb_api_key="False"
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
prepare tokenizer
Using DreamBooth method.
prepare images.
found directory D:\dataset\bernard\img_g4v2\30_bmaltais contains 23 image files
No caption file found for 23 images. Training will continue without captions for these images. If class token exists, it will be used. / 23枚の画像にキャプションファイルが見つかりませんでした。これら の画像についてはキャプションなしで学習を続行します。class tokenが存在する場合はそれを使います。
D:\dataset\bernard\img_g4v2\30_bmaltais\group-1-IMG_4573.jpg
D:\dataset\bernard\img_g4v2\30_bmaltais\group-1-IMG_5205.jpg
D:\dataset\bernard\img_g4v2\30_bmaltais\group-1-IMG_5271.jpg
D:\dataset\bernard\img_g4v2\30_bmaltais\group-1-IMG_5295~2.jpg
D:\dataset\bernard\img_g4v2\30_bmaltais\group-2-PXL_20221013_201259761_exported_350_1665713349611.jpg
D:\dataset\bernard\img_g4v2\30_bmaltais\group-2-PXL_20221017_234220629.PORTRAIT.jpg... and 18 more
690 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 4
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 1
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "D:\dataset\bernard\img_g4v2\30_bmaltais"
    image_count: 23
    num_repeats: 30
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: bmaltais
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 132.70it/s] 
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイ ズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (436, 602), count: 120
bucket 1: resolution (443, 591), count: 120
bucket 2: resolution (445, 590), count: 120
bucket 3: resolution (563, 466), count: 120
bucket 4: resolution (591, 443), count: 90
bucket 5: resolution (591, 444), count: 120
mean ar error (without repeats): 0.0004493282716215369
preparing accelerator
D:\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:258: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
Using accelerator 0.15.0 or above.
loading model for process 0/1
load StableDiffusion checkpoint: D:/models/v1-5-pruned.ckpt
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
CrossAttention.forward has been replaced to enable xformers.
import network module: lycoris.kohya
[Dataset 0]
caching latents.
0it [00:00, ?it/s]
Using rank adaptation algo: loha
Apply different lora dim for conv layer
Conv Dim: 8, Linear Dim: 32
Apply different alpha value for conv layer
Conv alpha: 4.0, Linear alpha: 16.0
Use Dropout value: 0.0
Create LyCORIS Module
create LyCORIS for Text Encoder: 72 modules.
Create LyCORIS Module
create LyCORIS for U-Net: 278 modules.
enable LyCORIS for text encoder
enable LyCORIS for U-Net
preparing optimizer, data loader etc.
Deprecated: use prepare_optimizer_params(text_encoder_lr, unet_lr, learning_rate) instead of prepare_optimizer_params(text_encoder_lr, unet_lr)
use Prodigy optimizer | {'decouple': True, 'weight_decay': 0.6, 'betas': (0.9, 0.99), 'use_bias_correction': True}
Using decoupled weight decay
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 690
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 173
  num epochs / epoch数: 3
  batch size per device / バッチサイズ: 4
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 518
steps:   0%|                                                                                                                                                                   | 0/518 [00:00<?, ?it/s]
epoch 1/3
```

In case it help, here is the full traceback:

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\kohya_ss\train_network.py:873 in <module>                                                     │
│                                                                                                  │
│   870 │   args = parser.parse_args()                                                             │
│   871 │   args = train_util.read_config_from_file(args, parser)                                  │
│   872 │                                                                                          │
│ ❱ 873 │   train(args)                                                                            │
│   874                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\train_network.py:662 in train                                                        │
│                                                                                                  │
│   659 │   │   │   │                                                                              │
│   660 │   │   │   │   # Predict the noise residual                                               │
│   661 │   │   │   │   with accelerator.autocast():                                               │
│ ❱ 662 │   │   │   │   │   noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).s   │
│   663 │   │   │   │                                                                              │
│   664 │   │   │   │   if args.v_parameterization:                                                │
│   665 │   │   │   │   │   # v-parameterization training                                          │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                 │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py:521 in forward                 │
│                                                                                                  │
│   518 │   model_forward = ConvertOutputsToFp32(model_forward)                                    │
│   519 │                                                                                          │
│   520 │   def forward(*args, **kwargs):                                                          │
│ ❱ 521 │   │   return model_forward(*args, **kwargs)                                              │
│   522 │                                                                                          │
│   523 │   # To act like a decorator so that it can be popped when doing `extract_model_from_pa   │
│   524 │   forward.__wrapped__ = model_forward                                                    │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py:509 in __call__                │
│                                                                                                  │
│   506 │   │   update_wrapper(self, model_forward)                                                │
│   507 │                                                                                          │
│   508 │   def __call__(self, *args, **kwargs):                                                   │
│ ❱ 509 │   │   return convert_to_fp32(self.model_forward(*args, **kwargs))                        │
│   510 │                                                                                          │
│   511 │   def __getstate__(self):                                                                │
│   512 │   │   raise pickle.PicklingError(                                                        │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py:14 in decorate_autocast            │
│                                                                                                  │
│    11 │   @functools.wraps(func)                                                                 │
│    12 │   def decorate_autocast(*args, **kwargs):                                                │
│    13 │   │   with autocast_instance:                                                            │
│ ❱  14 │   │   │   return func(*args, **kwargs)                                                   │
│    15 │   decorate_autocast.__script_unsupported = '@autocast() decorator is not supported in    │
│    16 │   return decorate_autocast                                                               │
│    17                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_condition.py:381 in forward          │
│                                                                                                  │
│   378 │   │   down_block_res_samples = (sample,)                                                 │
│   379 │   │   for downsample_block in self.down_blocks:                                          │
│   380 │   │   │   if hasattr(downsample_block, "has_cross_attention") and downsample_block.has   │
│ ❱ 381 │   │   │   │   sample, res_samples = downsample_block(                                    │
│   382 │   │   │   │   │   hidden_states=sample,                                                  │
│   383 │   │   │   │   │   temb=emb,                                                              │
│   384 │   │   │   │   │   encoder_hidden_states=encoder_hidden_states,                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                 │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:611 in forward             │
│                                                                                                  │
│    608 │   │   │   │   │   create_custom_forward(attn, return_dict=False), hidden_states, encod  │
│    609 │   │   │   │   )[0]                                                                      │
│    610 │   │   │   else:                                                                         │
│ ❱  611 │   │   │   │   hidden_states = resnet(hidden_states, temb)                               │
│    612 │   │   │   │   hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden  │
│    613 │   │   │                                                                                 │
│    614 │   │   │   output_states += (hidden_states,)                                             │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                 │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\diffusers\models\resnet.py:464 in forward                     │
│                                                                                                  │
│   461 │   │   │   input_tensor = self.downsample(input_tensor)                                   │
│   462 │   │   │   hidden_states = self.downsample(hidden_states)                                 │
│   463 │   │                                                                                      │
│ ❱ 464 │   │   hidden_states = self.conv1(hidden_states)                                          │
│   465 │   │                                                                                      │
│   466 │   │   if temb is not None:                                                               │
│   467 │   │   │   temb = self.time_emb_proj(self.nonlinearity(temb))[:, :, None, None]           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                 │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\utils\_contextlib.py:115 in decorate_context            │
│                                                                                                  │
│   112 │   @functools.wraps(func)                                                                 │
│   113 │   def decorate_context(*args, **kwargs):                                                 │
│   114 │   │   with ctx_factory():                                                                │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │
│   116 │                                                                                          │
│   117 │   return decorate_context                                                                │
│   118                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\lycoris\loha.py:214 in forward                                │
│                                                                                                  │
│   211 │   @torch.enable_grad()                                                                   │
│   212 │   def forward(self, x):                                                                  │
│   213 │   │   # print(torch.mean(torch.abs(self.orig_w1a.to(x.device) - self.hada_w1_a)), end=   │
│ ❱ 214 │   │   weight = self.org_module[0].weight.data + self.get_weight() * self.multiplier      │
│   215 │   │   bias = None if self.org_module[0].bias is None else self.org_module[0].bias.data   │
│   216 │   │   return self.op(                                                                    │
│   217 │   │   │   x,                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by bmaltais** [comment]
Also, if you want, I could provide a copy of the training dataset for testing. Might also be related to the optimized I use? I will test with non Dadaptation based optimizers...

**Comment by KohakuBlueleaf** [comment]
@bmaltais I pushed a fix for this

**Comment by bmaltais** [comment]
@KohakuBlueleaf Thank you for the fix, but it still fail with the same error ;-(

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\kohya_ss\train_network.py:873 in <module>                                                     │
│                                                                                                  │
│   870 │   args = parser.parse_args()                                                             │
│   871 │   args = train_util.read_config_from_file(args, parser)                                  │
│   872 │                                                                                          │
│ ❱ 873 │   train(args)                                                                            │
│   874                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\train_network.py:662 in train                                                        │
│                                                                                                  │
│   659 │   │   │   │                                                                              │
│   660 │   │   │   │   # Predict the noise residual                                               │
│   661 │   │   │   │   with accelerator.autocast():                                               │
│ ❱ 662 │   │   │   │   │   noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).s   │
│   663 │   │   │   │                                                                              │
│   664 │   │   │   │   if args.v_parameterization:                                                │
│   665 │   │   │   │   │   # v-parameterization training                                          │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                 │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py:521 in forward                 │
│                                                                                                  │
│   518 │   model_forward = ConvertOutputsToFp32(model_forward)                                    │
│   519 │                                                                                          │
│   520 │   def forward(*args, **kwargs):                                                          │
│ ❱ 521 │   │   return model_forward(*args, **kwargs)                                              │
│   522 │                                                                                          │
│   523 │   # To act like a decorator so that it can be popped when doing `extract_model_from_pa   │
│   524 │   forward.__wrapped__ = model_forward                                                    │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py:509 in __call__                │
│                                                                                                  │
│   506 │   │   update_wrapper(self, model_forward)                                                │
│   507 │                                                                                          │
│   508 │   def __call__(self, *args, **kwargs):                                                   │
│ ❱ 509 │   │   return convert_to_fp32(self.model_forward(*args, **kwargs))                        │
│   510 │                                                                                          │
│   511 │   def __getstate__(self):                                                                │
│   512 │   │   raise pickle.PicklingError(                                                        │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py:14 in decorate_autocast            │
│                                                                                                  │
│    11 │   @functools.wraps(func)                                                                 │
│    12 │   def decorate_autocast(*args, **kwargs):                                                │
│    13 │   │   with autocast_instance:                                                            │
│ ❱  14 │   │   │   return func(*args, **kwargs)                                                   │
│    15 │   decorate_autocast.__script_unsupported = '@autocast() decorator is not supported in    │
│    16 │   return decorate_autocast                                                               │
│    17                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_condition.py:381 in forward          │
│                                                                                                  │
│   378 │   │   down_block_res_samples = (sample,)                                                 │
│   379 │   │   for downsample_block in self.down_blocks:                                          │
│   380 │   │   │   if hasattr(downsample_block, "has_cross_attention") and downsample_block.has   │
│ ❱ 381 │   │   │   │   sample, res_samples = downsample_block(                                    │
│   382 │   │   │   │   │   hidden_states=sample,                                                  │
│   383 │   │   │   │   │   temb=emb,                                                              │
│   384 │   │   │   │   │   encoder_hidden_states=encoder_hidden_states,                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                 │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:611 in forward             │
│                                                                                                  │
│    608 │   │   │   │   │   create_custom_forward(attn, return_dict=False), hidden_states, encod  │
│    609 │   │   │   │   )[0]                                                                      │
│    610 │   │   │   else:                                                                         │
│ ❱  611 │   │   │   │   hidden_states = resnet(hidden_states, temb)                               │
│    612 │   │   │   │   hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden  │
│    613 │   │   │                                                                                 │
│    614 │   │   │   output_states += (hidden_states,)                                             │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                 │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\diffusers\models\resnet.py:464 in forward                     │
│                                                                                                  │
│   461 │   │   │   input_tensor = self.downsample(input_tensor)                                   │
│   462 │   │   │   hidden_states = self.downsample(hidden_states)                                 │
│   463 │   │                                                                                      │
│ ❱ 464 │   │   hidden_states = self.conv1(hidden_states)                                          │
│   465 │   │                                                                                      │
│   466 │   │   if temb is not None:                                                               │
│   467 │   │   │   temb = self.time_emb_proj(self.nonlinearity(temb))[:, :, None, None]           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                 │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\utils\_contextlib.py:115 in decorate_context            │
│                                                                                                  │
│   112 │   @functools.wraps(func)                                                                 │
│   113 │   def decorate_context(*args, **kwargs):                                                 │
│   114 │   │   with ctx_factory():                                                                │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │
│   116 │                                                                                          │
│   117 │   return decorate_context                                                                │
│   118                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\lycoris\loha.py:215 in forward                                │
│                                                                                                  │
│   212 │   def forward(self, x):                                                                  │
│   213 │   │   # print(torch.mean(torch.abs(self.orig_w1a.to(x.device) - self.hada_w1_a)), end=   │
│   214 │   │   weight = (                                                                         │
│ ❱ 215 │   │   │   self.org_module[0].weight.data                                                 │
│   216 │   │   │   + self.get_weight(self.org_module[0].weight.data) * self.multiplier            │
│   217 │   │   )                                                                                  │
│   218 │   │   bias = None if self.org_module[0].bias is None else self.org_module[0].bias.data   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The size of tensor a (3) must match the size of tensor b (2880) at non-singleton dimension 3
```

**Comment by KohakuBlueleaf** [comment]
Ok this may take me some time to fix jt

**Comment by bmaltais** [comment]
No worries. I also checked with the standard optimizer AdamW and I got the same error... so not related to the optimizer selection. Did not tought it would but wanted to eliminate that possibility.

**Comment by bmaltais** [comment]
Just tested LoKr and it also fails but with a different error:

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\kohya_ss\train_network.py:873 in <module>                                                     │
│                                                                                                  │
│   870 │   args = parser.parse_args()                                                             │
│   871 │   args = train_util.read_config_from_file(args, parser)                                  │
│   872 │                                                                                          │
│ ❱ 873 │   train(args)                                                                            │
│   874                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\train_network.py:644 in train                                                        │
│                                                                                                  │
│   641 │   │   │   │   │   │   )                                                                  │
│   642 │   │   │   │   │   else:                                                                  │
│   643 │   │   │   │   │   │   input_ids = batch["input_ids"].to(accelerator.device)              │
│ ❱ 644 │   │   │   │   │   │   encoder_hidden_states = train_util.get_hidden_states(args, input   │
│   645 │   │   │   │                                                                              │
│   646 │   │   │   │   # Sample noise that we'll add to the latents                               │
│   647 │   │   │   │   noise = torch.randn_like(latents, device=latents.device)                   │
│                                                                                                  │
│ D:\kohya_ss\library\train_util.py:3186 in get_hidden_states                                      │
│                                                                                                  │
│   3183 │   input_ids = input_ids.reshape((-1, tokenizer.model_max_length))  # batch_size*3, 77   │
│   3184 │                                                                                         │
│   3185 │   if args.clip_skip is None:                                                            │
│ ❱ 3186 │   │   encoder_hidden_states = text_encoder(input_ids)[0]                                │
│   3187 │   else:                                                                                 │
│   3188 │   │   enc_out = text_encoder(input_ids, output_hidden_states=True, return_dict=True)    │
│   3189 │   │   encoder_hidden_states = enc_out["hidden_states"][-args.clip_skip]                 │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                 │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py:521 in forward                 │
│                                                                                                  │
│   518 │   model_forward = ConvertOutputsToFp32(model_forward)                                    │
│   519 │                                                                                          │
│   520 │   def forward(*args, **kwargs):                                                          │
│ ❱ 521 │   │   return model_forward(*args, **kwargs)                                              │
│   522 │                                                                                          │
│   523 │   # To act like a decorator so that it can be popped when doing `extract_model_from_pa   │
│   524 │   forward.__wrapped__ = model_forward                                                    │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py:509 in __call__                │
│                                                                                                  │
│   506 │   │   update_wrapper(self, model_forward)                                                │
│   507 │                                                                                          │
│   508 │   def __call__(self, *args, **kwargs):                                                   │
│ ❱ 509 │   │   return convert_to_fp32(self.model_forward(*args, **kwargs))                        │
│   510 │                                                                                          │
│   511 │   def __getstate__(self):                                                                │
│   512 │   │   raise pickle.PicklingError(                                                        │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py:14 in decorate_autocast            │
│                                                                                                  │
│    11 │   @functools.wraps(func)                                                                 │
│    12 │   def decorate_autocast(*args, **kwargs):                                                │
│    13 │   │   with autocast_instance:                                                            │
│ ❱  14 │   │   │   return func(*args, **kwargs)                                                   │
│    15 │   decorate_autocast.__script_unsupported = '@autocast() decorator is not supported in    │
│    16 │   return decorate_autocast                                                               │
│    17                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:816 in forward      │
│                                                                                                  │
│    813 │   │   ```"""                                                                            │
│    814 │   │   return_dict = return_dict if return_dict is not None else self.config.use_return  │
│    815 │   │                                                                                     │
│ ❱  816 │   │   return self.text_model(                                                           │
│    817 │   │   │   input_ids=input_ids,                                                          │
│    818 │   │   │   attention_mask=attention_mask,                                                │
│    819 │   │   │   position_ids=position_ids,                                                    │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                 │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:725 in forward      │
│                                                                                                  │
│    722 │   │   │   # [bsz, seq_len] -> [bsz, 1, tgt_seq_len, src_seq_len]                        │
│    723 │   │   │   attention_mask = _expand_mask(attention_mask, hidden_states.dtype)            │
│    724 │   │                                                                                     │
│ ❱  725 │   │   encoder_outputs = self.encoder(                                                   │
│    726 │   │   │   inputs_embeds=hidden_states,                                                  │
│    727 │   │   │   attention_mask=attention_mask,                                                │
│    728 │   │   │   causal_attention_mask=causal_attention_mask,                                  │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                 │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:654 in forward      │
│                                                                                                  │
│    651 │   │   │   │   │   causal_attention_mask,                                                │
│    652 │   │   │   │   )                                                                         │
│    653 │   │   │   else:                                                                         │
│ ❱  654 │   │   │   │   layer_outputs = encoder_layer(                                            │
│    655 │   │   │   │   │   hidden_states,                                                        │
│    656 │   │   │   │   │   attention_mask,                                                       │
│    657 │   │   │   │   │   causal_attention_mask,                                                │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                 │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:383 in forward      │
│                                                                                                  │
│    380 │   │   residual = hidden_states                                                          │
│    381 │   │                                                                                     │
│    382 │   │   hidden_states = self.layer_norm1(hidden_states)                                   │
│ ❱  383 │   │   hidden_states, attn_weights = self.self_attn(                                     │
│    384 │   │   │   hidden_states=hidden_states,                                                  │
│    385 │   │   │   attention_mask=attention_mask,                                                │
│    386 │   │   │   causal_attention_mask=causal_attention_mask,                                  │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                 │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:272 in forward      │
│                                                                                                  │
│    269 │   │   bsz, tgt_len, embed_dim = hidden_states.size()                                    │
│    270 │   │                                                                                     │
│    271 │   │   # get query proj                                                                  │
│ ❱  272 │   │   query_states = self.q_proj(hidden_states) * self.scale                            │
│    273 │   │   key_states = self._shape(self.k_proj(hidden_states), -1, bsz)                     │
│    274 │   │   value_states = self._shape(self.v_proj(hidden_states), -1, bsz)                   │
│    275                                                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                 │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\lycoris\lokr.py:243 in forward                                │
│                                                                                                  │
│   240 │   │   return scaled, orig_norm*ratio                                                     │
│   241 │                                                                                          │
│   242 │   def forward(self, x):                                                                  │
│ ❱ 243 │   │   weight = self.org_module[0].weight.data + self.get_weight() * self.multiplier      │
│   244 │   │   bias = None if self.org_module[0].bias is None else self.org_module[0].bias.data   │
│   245 │   │   return self.op(                                                                    │
│   246 │   │   │   x,                                                                             │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\lycoris\lokr.py:206 in get_weight                             │
│                                                                                                  │
│   203 │   │   self.org_module[0].forward = self.forward                                          │
│   204 │                                                                                          │
│   205 │   def get_weight(self):                                                                  │
│ ❱ 206 │   │   weight = make_kron(                                                                │
│   207 │   │   │   0,                                                                             │
│   208 │   │   │   self.lokr_w1 if self.use_w1 else self.lokr_w1_a@self.lokr_w1_b,                │
│   209 │   │   │   (self.lokr_w2 if self.use_w2                                                   │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\lycoris\lokr.py:63 in make_kron                               │
│                                                                                                  │
│    60 │   if len(w2.shape) == 4:                                                                 │
│    61 │   │   w1 = w1.unsqueeze(2).unsqueeze(2)                                                  │
│    62 │   w2 = w2.contiguous()                                                                   │
│ ❱  63 │   return orig_weight + torch.kron(w1, w2).reshape(orig_weight.shape)*scale               │
│    64                                                                                            │
│    65                                                                                            │
│    66 class LokrModule(nn.Module):                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'int' object has no attribute 'shape'
```

**Comment by KohakuBlueleaf** [comment]
@bmaltais I pushed another fix for loha and lokr, should work

**Comment by bmaltais** [comment]
OK, will test soon... once my current training is completed.

**Comment by bmaltais** [comment]
@KohakuBlueleaf Moving closer, but new error for LoHA:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\kohya_ss\train_network.py:873 in <module>                                                     │
│                                                                                                  │
│   870 │   args = parser.parse_args()                                                             │
│   871 │   args = train_util.read_config_from_file(args, parser)                                  │
│   872 │                                                                                          │
│ ❱ 873 │   train(args)                                                                            │
│   874                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\train_network.py:683 in train                                                        │
│                                                                                                  │
│   680 │   │   │   │                                                                              │
│   681 │   │   │   │   loss = loss.mean()  # 平均なのでbatch_sizeで割る必要なし                   │
│   682 │   │   │   │                                                                              │
│ ❱ 683 │   │   │   │   accelerator.backward(loss)                                                 │
│   684 │   │   │   │   if accelerator.sync_gradients and args.max_grad_norm != 0.0:               │
│   685 │   │   │   │   │   params_to_clip = network.get_trainable_params()                        │
│   686 │   │   │   │   │   accelerator.clip_grad_norm_(params_to_clip, args.max_grad_norm)        │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:1745 in backward                    │
│                                                                                                  │
│   1742 │   │   elif self.scaler is not None:                                                     │
│   1743 │   │   │   self.scaler.scale(loss).backward(**kwargs)                                    │
│   1744 │   │   else:                                                                             │
│ ❱ 1745 │   │   │   loss.backward(**kwargs)                                                       │
│   1746 │                                                                                         │
│   1747 │   def unscale_gradients(self, optimizer=None):                                          │
│   1748 │   │   """                                                                               │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\_tensor.py:487 in backward                              │
│                                                                                                  │
│    484 │   │   │   │   create_graph=create_graph,                                                │
│    485 │   │   │   │   inputs=inputs,                                                            │
│    486 │   │   │   )                                                                             │
│ ❱  487 │   │   torch.autograd.backward(                                                          │
│    488 │   │   │   self, gradient, retain_graph, create_graph, inputs=inputs                     │
│    489 │   │   )                                                                                 │
│    490                                                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\autograd\__init__.py:200 in backward                    │
│                                                                                                  │
│   197 │   # The reason we repeat same the comment below is that                                  │
│   198 │   # some Python versions print out the first line of a multi-line function               │
│   199 │   # calls in the traceback and some print out the last line                              │
│ ❱ 200 │   Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the bac   │
│   201 │   │   tensors, grad_tensors_, retain_graph, create_graph, inputs,                        │
│   202 │   │   allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to ru   │
│   203                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: function HadaWeightBackward returned a gradient different than None at position 1, but the corresponding forward input was not a Variable

**Comment by bmaltais** [comment]
Tested LoKr and it will train now. So only an issue with LoHA at this point.

**Comment by bmaltais** [comment]
I spoke too fast... LoKr errored out in the middle of training:

```
steps:  14%|█████████▊                                                           | 58/410 [00:56<05:41,  1.03it/s, Average key norm=tensor(0.1404, device='cuda:0'), Keys Scaled=tensor(0), loss=0.119]╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\kohya_ss\train_network.py:873 in <module>                                                     │
│                                                                                                  │
│   870 │   args = parser.parse_args()                                                             │
│   871 │   args = train_util.read_config_from_file(args, parser)                                  │
│   872 │                                                                                          │
│ ❱ 873 │   train(args)                                                                            │
│   874                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\train_network.py:693 in train                                                        │
│                                                                                                  │
│   690 │   │   │   │   optimizer.zero_grad(set_to_none=True)                                      │
│   691 │   │   │                                                                                  │
│   692 │   │   │   if args.scale_weight_norms:                                                    │
│ ❱ 693 │   │   │   │   keys_scaled, mean_norm, maximum_norm = network.apply_max_norm_regulariza   │
│   694 │   │   │   │   │   args.scale_weight_norms, accelerator.device                            │
│   695 │   │   │   │   )                                                                          │
│   696 │   │   │   │   max_mean_logs = {"Keys Scaled": keys_scaled, "Average key norm": mean_no   │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\lycoris\kohya.py:280 in apply_max_norm_regularization         │
│                                                                                                  │
│   277 │   │   norms = []                                                                         │
│   278 │   │   for model in self.unet_loras:                                                      │
│   279 │   │   │   if hasattr(model, 'apply_max_norm'):                                           │
│ ❱ 280 │   │   │   │   scaled, norm = model.apply_max_norm(max_norm_value, device)                │
│   281 │   │   │   │   norms.append(norm)                                                         │
│   282 │   │   │   │   key_scaled += scaled                                                       │
│   283                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\utils\_contextlib.py:115 in decorate_context            │
│                                                                                                  │
│   112 │   @functools.wraps(func)                                                                 │
│   113 │   def decorate_context(*args, **kwargs):                                                 │
│   114 │   │   with ctx_factory():                                                                │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │
│   116 │                                                                                          │
│   117 │   return decorate_context                                                                │
│   118                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\lycoris\lokr.py:233 in apply_max_norm                         │
│                                                                                                  │
│   230 │   │   if scaled:                                                                         │
│   231 │   │   │   modules = (4 - self.use_w1 - self.use_w2 + (not self.use_w2 and self.cp))      │
│   232 │   │   │   if self.use_w1:                                                                │
│ ❱ 233 │   │   │   │   self.lokr_w1_a *= ratio**(1/modules)                                       │
│   234 │   │   │   │   self.lokr_w1_b *= ratio**(1/modules)                                       │
│   235 │   │   │   else:                                                                          │
│   236 │   │   │   │   self.lokr_w1 *= ratio**(1/modules)                                         │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1614 in __getattr__                │
│                                                                                                  │
│   1611 │   │   │   modules = self.__dict__['_modules']                                           │
│   1612 │   │   │   if name in modules:                                                           │
│   1613 │   │   │   │   return modules[name]                                                      │
│ ❱ 1614 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                  │
│   1615 │   │   │   type(self).__name__, name))                                                   │
│   1616 │                                                                                         │
│   1617 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'LokrModule' object has no attribute 'lokr_w1_a'
```
